version: "3.8"

networks:
  weather-network:
    driver: bridge

volumes:
  weather-data:
    name: weather-data

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres-container
    ports:
      - "5432:5432"
    networks:
      - weather-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: veiculos
      POSTGRES_PASSWORD: 102030
    expose:
      - 5432

  
  web:
    build: .
    container_name: web
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=veiculos
      - POSTGRES_HOST=postgres-container
      - POSTGRES_PASSWORD=102030
    ports:
      - '4000:4000'
    networks:
      - weather-network
    links:
      - postgres      
    depends_on:
      - postgres
    restart: always